- name: Remove existing MongoDB container if any
  community.docker.docker_container:
    name: mongodb_container
    state: absent
    force_kill: true

- name: Pull MongoDB image
  community.docker.docker_image:
    name: mongo
    source: pull

- name: Run MongoDB container
  community.docker.docker_container:
    name: mongodb_container
    image: mongo
    state: started
    restart_policy: always
    ports:
      - "27017:27017"
    networks:
      - name: app-net
    
    #Ensure uploaded products persist
    volumes:
      - mongo-data:/data/db   
