apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: yolo-app
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5100
      targetPort: 5100
      protocol: TCP
  type: ClusterIP

