apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  namespace: yolo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kipyegonrotich/yolo-backend:v1.0.2
          ports:
            - containerPort: 5100
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/yolodb
              
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 5100
            initialDelaySeconds: 10
            periodSeconds: 10
            
