apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    description: "Public-facing service for YOLO frontend"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

